select * from TransformPurchaseOrdersVendorContract

select * from TransformPurchaseOrdersVendorContractLineItems

select * from TransformPurchaseOrdersVendorContractFiles

select * from TransformPurchaseOrdersVendorContractAttributes
