USE [AssetWorksConversion]
GO

/****** Object:  Table [dbo].[TransformMUNISPurchaseOrders]    Script Date: 09/15/2015 10:50:41 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TransformMUNISPurchaseOrders]') AND TYPE IN (N'U'))
DROP TABLE [dbo].[TransformMUNISPurchaseOrders]
GO

USE [AssetWorksConversion]
GO

/****** Object:  Table [dbo].[TransformMUNISPurchaseOrders]    Script Date: 09/15/2015 10:50:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TransformMUNISPurchaseOrders](
	[Link] [nvarchar](255) NULL,
	[Record Type] [nvarchar](255) NULL,
	[Purchase Order] [float] NULL,
	[Fiscal Year] [float] NULL,
	[Total Ordered] [float] NULL,
	[Total Liquidated] [float] NULL,
	[Total Balance] [float] NULL,
	[Create Date] [datetime] NULL,
	[Change Date] [datetime] NULL,
	[Vendor] [float] NULL,
	[Alpha Sort] [nvarchar](255) NULL,
	[DBA] [nvarchar](255) NULL,
	[Name] [nvarchar](255) NULL,
	[Name2] [nvarchar](255) NULL,
	[Address Line 1] [nvarchar](255) NULL,
	[Address Line 2] [nvarchar](255) NULL,
	[Address Line 3] [nvarchar](255) NULL,
	[City] [nvarchar](255) NULL,
	[State] [nvarchar](255) NULL,
	[Zip Code] [nvarchar](255) NULL,
	[Country] [nvarchar](255) NULL,
	[Status] [nvarchar](255) NULL,
	[General Commodity] [nvarchar](255) NULL,
	[Requisition] [float] NULL,
	[Department Location] [nvarchar](255) NULL,
	[Review Code] [nvarchar](255) NULL,
	[Contract] [nvarchar](255) NULL,
	[FOB] [nvarchar](255) NULL,
	[FREIGHT TERMS] [nvarchar](255) NULL,
	[DELIVERY METHOD] [nvarchar](255) NULL,
	[SELECTION METHOD] [nvarchar](255) NULL,
	[IDA] [nvarchar](255) NULL,
	[PREPAY?] [nvarchar](255) NULL,
	[PAYMENT DISCOUNT] [nvarchar](255) NULL,
	[DISCOUNT DAYS] [nvarchar](255) NULL,
	[NET DAYS] [nvarchar](255) NULL,
	[CONTRACT NUMBER] [nvarchar](255) NULL,
	[CONTRACT EXPIRATION DATE] [nvarchar](255) NULL,
	[1VENDOR$QUOTE] [nvarchar](255) NULL,
	[2VENDOR$QUOTE] [nvarchar](255) NULL,
	[3VENDOR$QUOTE] [nvarchar](255) NULL,
	[DEPT'S ORIGINAL ESTIMATE] [nvarchar](255) NULL,
	[TERM TYPE] [nvarchar](255) NULL,
	[CW REQ# (PUBLIC WORKS ONLY)] [nvarchar](255) NULL,
	[CW PART# (PUBLIC WORKS ONLY)] [nvarchar](255) NULL,
	[REVENUE?] [nvarchar](255) NULL,
	[PO Line Number] [float] NULL,
	[Quantity] [float] NULL,
	[Unit of Measure] [nvarchar](255) NULL,
	[Unit Price] [float] NULL,
	[Freight] [float] NULL,
	[Discount %] [float] NULL,
	[Discount Amount] [float] NULL,
	[Credit] [float] NULL,
	[Net Price] [float] NULL,
	[PO Detail Description] [nvarchar](255) NULL,
	[Description] [nvarchar](255) NULL,
	[PO Detail Commodity] [nvarchar](255) NULL,
	[Inventory Item] [nvarchar](255) NULL,
	[Inventory Location] [nvarchar](255) NULL,
	[Product ID] [nvarchar](255) NULL,
	[Product Description] [nvarchar](255) NULL,
	[Manufacturer] [nvarchar](255) NULL,
	[Manufacturer Item] [nvarchar](255) NULL,
	[Vendor Item] [nvarchar](255) NULL,
	[1099] [nvarchar](255) NULL,
	[Fixed Asset] [nvarchar](255) NULL,
	[Request By] [nvarchar](255) NULL,
	[Required By] [datetime] NULL,
	[Dept/Loc] [nvarchar](255) NULL,
	[Bid Number] [nvarchar](255) NULL,
	[Work Order Number] [nvarchar](255) NULL,
	[Work Order Task] [nvarchar](255) NULL,
	[Notify Buyer] [nvarchar](255) NULL,
	[Risk Claim] [nvarchar](255) NULL,
	[Acct Line Number] [float] NULL,
	[PA Type] [nvarchar](255) NULL,
	[Project Account] [nvarchar](255) NULL,
	[GL Account] [nvarchar](255) NULL,
	[Org] [nvarchar](255) NULL,
	[Object] [nvarchar](255) NULL,
	[Project] [nvarchar](255) NULL,
	[Account Description] [nvarchar](255) NULL,
	[Account Amt] [float] NULL,
	[PA Bud Code] [nvarchar](255) NULL,
	[Budget Code] [nvarchar](255) NULL,
	[CreateDt] [datetime] NOT NULL
) ON [PRIMARY]
GO

-- Copy from Staging to Transform
INSERT INTO TransformMUNISPurchaseOrders
SELECT
	munis.[Link],
	munis.[Record Type],
	munis.[Purchase Order],
	munis.[Fiscal Year],
	munis.[Total Ordered],
	munis.[Total Liquidated],
	munis.[Total Balance],
	munis.[Create Date],
	munis.[Change Date],
	munis.Vendor,
	munis.[Alpha Sort],
	munis.DBA,
	munis.Name,
	munis.Name2,
	munis.[Address Line 1],
	munis.[Address Line 2],
	munis.[Address Line 3],
	munis.City,
	munis.[State],
	munis.[Zip Code],
	munis.Country,
	munis.[Status],
	munis.[General Commodity],
	munis.Requisition,
	munis.[Department Location],
	munis.[Review Code],
	munis.[Contract],
	munis.FOB,
	munis.[FREIGHT TERMS],
	munis.[DELIVERY METHOD],
	munis.[SELECTION METHOD],
	munis.IDA,
	munis.[PREPAY?],
	munis.[PAYMENT DISCOUNT],
	munis.[DISCOUNT DAYS],
	munis.[NET DAYS],
	munis.[CONTRACT NUMBER],
	munis.[CONTRACT EXPIRATION DATE],
	munis.[1VENDOR$QUOTE],
	munis.[2VENDOR$QUOTE],
	munis.[3VENDOR$QUOTE],
	munis.[DEPT'S ORIGINAL ESTIMATE],
	munis.[TERM TYPE],
	munis.[CW REQ# (PUBLIC WORKS ONLY)],
	munis.[CW PART# (PUBLIC WORKS ONLY)],
	munis.[REVENUE?],
	munis.[PO Line Number],
	munis.Quantity,
	munis.[Unit of Measure],
	munis.[Unit Price],
	munis.Freight,
	munis.[Discount %],
	munis.[Discount Amount],
	munis.Credit,
	munis.[Net Price],
	munis.[PO Detail Description],
	munis.[Description],
	munis.[PO Detail Commodity],
	munis.[Inventory Item],
	munis.[Inventory Location],
	munis.[Product ID],
	munis.[Product Description],
	munis.Manufacturer,
	munis.[Manufacturer Item],
	munis.[Vendor Item],
	munis.[1099],
	munis.[Fixed Asset],
	munis.[Request By],
	munis.[Required By],
	munis.[Dept/Loc],
	munis.[Bid Number],
	munis.[Work Order Number],
	munis.[Work Order Task],
	munis.[Notify Buyer],
	munis.[Risk Claim],
	munis.[Acct Line Number],
	munis.[PA Type],
	munis.[Project Account],
	munis.[GL Account],
	munis.Org,
	munis.[Object],
	munis.Project,
	munis.[Account Description],
	munis.[Account Amt],
	munis.[PA Bud Code],
	munis.[Budget Code],
	GETDATE()
FROM STAGING_TransformMUNISPurchaseOrders munis
GO
