--
TRUNCATE TABLE TransformWorkOrderCenter
TRUNCATE TABLE TransformWorkOrderCenterTasks
TRUNCATE TABLE TransformWorkOrderCenterLabor
TRUNCATE TABLE TransformWorkOrderCenterParts
TRUNCATE TABLE TransformWorkOrderCenterCommercial

EXEC spTransformWorkOrderCenter
EXEC spTransformWorkOrderCenterTasks
EXEC spTransformWorkOrderCenterLabor
EXEC spTransformWorkOrderCenterCommercial

--
SELECT * FROM TransformWorkOrderCenter
SELECT * FROM TransformWorkOrderCenterTasks
SELECT * FROM TransformWorkOrderCenterLabor ORDER BY WorkOrderNumber, LaborDt DESC
SELECT * FROM TransformWorkOrderCenterParts
SELECT * FROM TransformWorkOrderCenterCommercial
