--
TRUNCATE TABLE TransformWorkOrderCenter
TRUNCATE TABLE TransformWorkOrderCenterTasks
TRUNCATE TABLE TransformWorkOrderCenterLabor
TRUNCATE TABLE TransformWorkOrderCenterParts
TRUNCATE TABLE TransformWorkOrderCenterCommercial
TRUNCATE TABLE TransformWorkOrderCenterStandardJobs

EXEC spTransformWorkOrderCenter
EXEC spTransformWorkOrderCenterTasks
EXEC spTransformWorkOrderCenterLabor
EXEC spTransformWorkOrderCenterParts
EXEC spTransformWorkOrderCenterCommercial
EXEC spTransformWorkOrderCenterStandardJobs

--
SELECT * FROM TransformWorkOrderCenter
SELECT * FROM TransformWorkOrderCenterTasks
SELECT * FROM TransformWorkOrderCenterLabor ORDER BY WorkOrderNumber, LaborDt DESC
SELECT * FROM TransformWorkOrderCenterParts
SELECT * FROM TransformWorkOrderCenterCommercial
SELECT * FROM TransformWorkOrderCenterStandardJobs
