--
TRUNCATE TABLE TransformWorkOrderCenter
TRUNCATE TABLE TransformWorkOrderCenterTasks
TRUNCATE TABLE TransformWorkOrderCenterLabor

EXEC spTransformWorkOrderCenter
EXEC spTransformWorkOrderCenterTasks
EXEC spTransformWorkOrderCenterLabor

