--
TRUNCATE TABLE TransformPurchaseOrders
TRUNCATE TABLE TransformPurchaseOrdersLineItems
TRUNCATE TABLE TransformPurchaseOrdersEnterprisePurchasingReceipts
TRUNCATE TABLE TransformPurchaseOrdersVendorContract
TRUNCATE TABLE TransformPurchaseOrdersVendorContractLineItems
TRUNCATE TABLE TransformPurchaseOrdersVendorContractAttributes

EXEC spTransformPurchaseOrders
EXEC spTransformPurchaseOrdersLineItems
EXEC spTransformPurchaseOrdersEnterprisePurchasingReceipts
EXEC spTransformPurchaseOrdersVendorContract
EXEC spTransformPurchaseOrdersVendorContractLineItems
EXEC spTransformPurchaseOrdersVendorContractAttributes

SELECT * FROM TransformPurchaseOrders
SELECT * FROM TransformPurchaseOrdersLineItems
SELECT * FROM TransformPurchaseOrdersEnterprisePurchasingReceipts
SELECT * FROM TransformPurchaseOrdersVendorContract
SELECT * FROM TransformPurchaseOrdersVendorContractLineItems
SELECT * FROM TransformPurchaseOrdersVendorContractAttributes