USE [AssetWorksConversion]
GO

/****** Object:  Table [dbo].[TransformEquipmentHydrantValueEquipmentType] Script Date: 02/09/2015 07:01:19 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TransformEquipmentHydrantValueEquipmentType]') AND type in (N'U'))
DROP TABLE [dbo].[TransformEquipmentHydrantValueEquipmentType]
GO

/****** Object:  Table [dbo].[TransformEquipmentHydrantValueEquipmentType] Script Date: 02/09/2015 07:01:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TransformEquipmentHydrantValueEquipmentType](
	[HYD_MAKE] [varchar](12) NULL,
	[EquipmentType] [varchar] (30) NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

-- INSERT
INSERT INTO [AssetWorksConversion].[dbo].[TransformEquipmentHydrantValueEquipmentType]
           ([HYD_MAKE]
           ,[EquipmentType])
VALUES
	('DARLING 73-3', 'HYDRANT DARLING'),
	('DARLING,M73', 'HYDRANT DARLING'),
	('DARLING,M-73', 'HYDRANT DARLING'),
	('KENNEDY', 'HYDRANT KENNEDY K81'),
	('', 'HYDRANT DARLING'),
	('DARLING MK73', 'HYDRANT DARLING'),
	('DARLING M73', 'HYDRANT DARLING'),
	('DARLING,MK73', 'HYDRANT DARLING'),
	('DARLING B52B', 'HYDRANT DARLING'),
	('MK 73', 'HYDRANT DARLING'),
	('DARLING 73', 'HYDRANT DARLING'),
	('DARLING C', 'HYDRANT DARLING'),
	('AVK 2780', 'HYDRANT AVK 2780'),
	('DARLING', 'HYDRANT DARLING'),
	('DARLING,73-1', 'HYDRANT DARLING 73-1'),
	('DARLING 73-1', 'HYDRANT DARLING 73-1'),
	('DARLING 73 1', 'HYDRANT DARLING 73-1'),
	('DARLING,73 1', 'HYDRANT DARLING 73-1'),
	('DARL M73-1', 'HYDRANT DARLING 73-1'),
	('DARLING 73-2', 'HYDRANT DARLING 73-2'),
	('AFC 73-5', 'HYDRANT DARLING 73-5'),
	('AFC M73-5', 'HYDRANT DARLING 73-5'),
	('DARLING 73-5', 'HYDRANT DARLING 73-5'),
	('DARLING M735', 'HYDRANT DARLING 73-5'),
	('DARLING B50', 'HYDRANT DARLING B50'),
	('DARLING,B50', 'HYDRANT DARLING B50'),
	('B.50', 'HYDRANT DARLING B50'),
	('DARLING, B50', 'HYDRANT DARLING B50'),
	('DARLINGB-50', 'HYDRANT DARLING B50'),
	('DARLING B50B', 'HYDRANT DARLING B50B'),
	('DARLING B62B', 'HYDRANT DARLING B62B'),
	('DARLING SB', 'HYDRANT DARLING SB'),
	('DRESSER M&H', 'HYDRANT DRESSER M&H'),
	('KENNEDY K11', 'HYDRANT KENNEDY K11'),
	('KENNEDY K81', 'HYDRANT KENNEDY K81'),
	('KENNEDY K-81', 'HYDRANT KENNEDY K81'),
	('KENNEDY,K81A', 'HYDRANT KENNEDY K81'),
	('KENNEDY 81A', 'HYDRANT KENNEDY K81'),
	('KENNEDY K81A', 'HYDRANT KENNEDY K81'),
	('KENNEDY K81D', 'HYDRANT KENNEDY K81'),
	('KENNDEY K81A', 'HYDRANT KENNEDY K81'),
	('MUELLER', 'HYDRANT MUELLER'),
	('MUELLER SC', 'HYDRANT MUELLER'),
	('SMITH', 'HYDRANT SMITH'),
	('SMITH SMALL', 'HYDRANT SMITH  SMALL'),
	('SMITH  SMALL', 'HYDRANT SMITH  SMALL'),
	('SMITH SB', 'HYDRANT SMITH SB'),
	('WATEROUS PAC', 'HYDRANT WATEROUS PAC')
GO
